# Generated by Django 5.0.4 on 2024-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_students_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
    ]
