# Generated by Django 5.0.4 on 2024-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='flag',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
