# Generated by Django 5.0.4 on 2024-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_students_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookId', models.IntegerField()),
                ('bookName', models.CharField(max_length=100)),
                ('authorName', models.CharField(max_length=100)),
                ('bookCount', models.IntegerField()),
                ('bookTaken', models.BooleanField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
