# Generated by Django 5.0.4 on 2024-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='images',
            field=models.ImageField(default='', upload_to='books/'),
            preserve_default=False,
        ),
    ]
