# Generated by Django 5.0.4 on 2024-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_books_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookTaken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
