# Generated by Django 5.0.4 on 2024-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_books_booktaken_alter_students_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='lending_info',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
