# Generated by Django 5.0.4 on 2024-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_books_lending_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookCount',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='books',
            name='lending_info',
            field=models.JSONField(default=list),
        ),
    ]
